---
image: "registry.gitlab.com/mullholland/docker-molecule-github-action"

services:
  - docker:dind

stages:
  - linting
  - "default-previous"
  - "default-current"
  - "default-next"
  - "cluster-previous"
  - "cluster-current"
  - "cluster-next"
  - "cluster_notransit-previous"
  - "cluster_notransit-current"
  - "cluster_notransit-next"

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1
  ANSIBLE_FORCE_COLOR: 1

linting:
  stage: linting
  variables:
    COMMAND: "lint"
  script:
    - "command=${COMMAND} /opt/molecule.sh"


"default-previous":
  needs:
    - "linting"
  stage: "default-previous"
  variables:
    SCENARIO: "default"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"default-current":
  needs:
    - "linting"
  stage: "default-current"
  variables:
    SCENARIO: "default"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"default-next":
  needs:
    - "linting"
  stage: "default-next"
  variables:
    SCENARIO: "default"
    ANSIBLE: "next"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"cluster-previous":
  needs:
    - "linting"
  stage: "cluster-previous"
  variables:
    SCENARIO: "cluster"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"cluster-current":
  needs:
    - "linting"
  stage: "cluster-current"
  variables:
    SCENARIO: "cluster"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"cluster-next":
  needs:
    - "linting"
  stage: "cluster-next"
  variables:
    SCENARIO: "cluster"
    ANSIBLE: "next"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"cluster_notransit-previous":
  needs:
    - "linting"
  stage: "cluster_notransit-previous"
  variables:
    SCENARIO: "cluster_notransit"
    ANSIBLE: "previous"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"cluster_notransit-current":
  needs:
    - "linting"
  stage: "cluster_notransit-current"
  variables:
    SCENARIO: "cluster_notransit"
    ANSIBLE: "current"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"

"cluster_notransit-next":
  needs:
    - "linting"
  stage: "cluster_notransit-next"
  variables:
    SCENARIO: "cluster_notransit"
    ANSIBLE: "next"
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  parallel:
    matrix:
      - PLATFORM: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length
  script:
    - "scenario=${SCENARIO} ansible=${ANSIBLE} platform=${PLATFORM} /opt/molecule.sh"
