---
- name: select leader if vault_leader is unset
  ansible.builtin.set_fact:
    vault_leader: "{{ inventory_hostname }}"
    vault_transit_server: "{{ inventory_hostname }}"
  run_once: true
  when:
    - vault_leader is not defined

- name: print elected leader
  ansible.builtin.debug:
    msg: "{{ vault_leader }}"
