---
molecule_exceptions:
  - variation: centos-stream9
    reason: "No hashicorp Repository"
molecule_scenarios:
  - scenario: "default"
    ansible: ["2.10", "2.11", "2.12"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "fedora34"
      - "fedora35"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
  - scenario: "cluster"
    ansible: ["2.9", "2.10", "2.11"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "fedora34"
      - "fedora35"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
  - scenario: "cluster_notransit"
    ansible: ["2.9", "2.10", "2.11"]
    platforms:
      - "debian9"
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "centos7"
      - "centos-stream8"
      - "ubi8"
      - "fedora34"
      - "fedora35"
      - "amazonlinux"
      - "rockylinux8"
      - "almalinux8"
