---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    molecule_service: "vault"
    molecule_package: "vault"
    molecule_config: "/etc/vault.d/"
    molecule_vault_api_addr: "http://127.0.0.1:8200"

  tasks:
    - name: SmokeTests
      debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check vault package is installed
      ansible.builtin.package:
        name: "{{ molecule_package }}"
        state: present
      register: package_installed
      failed_when: (package_installed is changed) or (package_installed is failed)

    - name: check /etc/vault.d/vault.hcl conf file
      lineinfile:
        name: "{{ molecule_config }}/vault.hcl"
        line: "# Ansible managed: Do NOT edit this file manually!"
        state: present
        owner: "vault"
        group: "vault"
        mode: "0640"
      check_mode: true
      register: molecule_hcl
      failed_when: (molecule_hcl is changed) or (molecule_hcl is failed)

    - name: check /etc/vault.d/vault.env file
      lineinfile:
        name: "{{ molecule_config }}/vault.env"
        line: "# Ansible managed: Do NOT edit this file manually!"
        state: present
        owner: "vault"
        group: "vault"
        mode: "0640"
      check_mode: true
      register: molecule_env
      failed_when: (molecule_env is changed) or (molecule_env is failed)

    - name: check vault daemon
      service:
        name: "{{ molecule_package }}"
        state: started
        enabled: true
      check_mode: true
      register: molecule_service
      failed_when: (molecule_service is changed) or (molecule_service is failed)

    - name: check backup script
      lineinfile:
        name: "/usr/sbin/vault_backup.sh"
        line: "BACKUP_DIR='/opt/vault/backup'"
        state: present
        owner: "vault"
        group: "vault"
        mode: "0750"
      check_mode: true
      register: molecule_backup
      failed_when: (molecule_backup is changed) or (molecule_backup is failed)

    - name: check backup cron
      ansible.builtin.cron:
        name: "Vault Backup"
        cron_file: "vault"
        minute: "0,30"
        hour: "*"
        day: "*"
        job: "/usr/sbin/vault_backup.sh"
        user: "root"
      check_mode: true
      register: molecule_backup_cron
      failed_when: (molecule_backup_cron is changed) or (molecule_backup_cron is failed)

    # This should succeed regardless of seal state
    - name: Vault API reachable?
      # Attempt to help with long lines > 160 issues
      uri:
        url: "{{ molecule_vault_api_addr }}/v1/sys/health"
        method: GET
        # 200 if initialized, unsealed, and active
        # 429 if unsealed and standby
        # 472 if data recovery mode replication secondary and active
        # 473 if performance standby
        # 501 if not initialized
        # 503 if sealed
        # See: https://www.vaultproject.io/api/system/health.html
        status_code: 200, 429, 472, 473, 501, 503
        body_format: json
      register: check_result
      retries: 6
      until: check_result is succeeded
      delay: 10
      changed_when: false

    - name: Run /usr/sbin/vault_backup.sh script
      command: "/usr/sbin/vault_backup.sh"
      register: backup_run

    - name: Test /usr/sbin/vault_backup.sh script returncode
      fail:
        msg: "The script did not run successfully"
      when: backup_run.rc != 0
