---
# Ansible managed

name: "Ansible Molecule (2.10/default)"

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:
    types: [assigned]
  schedule:
    - cron: '43 22 22 * *'

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.2.3
        with:
          command: lint
          scenario: "default"
          ansible: "2.10"

  "default_210":
    needs:
      - linting
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        platform: [debian9, debian10, debian11, ubuntu1804, ubuntu2004, centos7, centos-stream8, centos-stream9, ubi8, fedora34, fedora35, amazonlinux, rockylinux8, almalinux8]  # yamllint disable-line rule:line-length

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: mullholland/molecule-github-action@v0.2.3
        with:
          namespace: "ghcr.io/mullholland"
          scenario: "default"
          ansible: "2.10"
          platform: "${{ matrix.platform }}"
